In [1]:
import os
import sys
# Agregar el directorio raíz del proyecto al path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)
    
    
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
dict_de_boyas = {}

### 2. OLEAJE

In [ ]:
# 1.1. p1: Cargar crudo pkl 
nombre = "BMT3-04-T45_C"
archivos_csv = "msj3_crudo_unido_realt_2026032416_2026062223.pkl"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_4.2\\2026\\06. Junio\\BMT3-04-T45\\DATOS"
df_pkl_crudo_realt = cargar_pickle_oleaje(ruta_a_carpeta, archivos_csv)
dict_de_boyas[nombre] = df_pkl_crudo_realt # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_crudo_realt.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2026-03-24 16:00:00  1.16  1.96  6.9  50.0    32.5
1 2026-03-24 17:00:00  1.18  1.76  6.9  49.7    31.4

In [6]:
# 1.5. p1: Cargar NETCDF de corrientes 
nombre = "BMT3-04-T45_NC"
nombre_de_archivo = "BMT3-04-T45-TRIAXYSG3-NS09173-Z0-REALT-20260324-20260622.nc"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_4.2\\2026\\06. Junio\\BMT3-04-T45\\DATOS"
df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2026-03-24 16:00:00  1.16  1.96  6.9  50.0    32.5
1 2026-03-24 17:00:00  1.18  1.76  6.9  49.7    31.4

In [10]:
df_nc.tail(2)

                   tspan    Hs  Hmax   Tp        dir     vardir
2230 2026-06-08 22:00:00  1.33  2.18  6.7  45.200001  18.799999
2231 2026-06-08 23:00:00  1.31  2.08  6.9  48.799999  21.299999

In [7]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BMT3-04-T45_datos_word_2026032416_2026062223.xlsx", variables="oleaje")

NAM correcto

  Variable  esperados  validados  porcentaje_validados
0       Hs       2168     2166.0             99.907749
1       Hm       2168     2166.0             99.907749
2       Tp       2168     2166.0             99.907749
3      dir       2168     2166.0             99.907749
4   vardir       2168     2166.0             99.907749
5  dirspec       2168     2048.0             94.464945

In [8]:
# 1.5. p1: Cargar NETCDF de corrientes 
nombre = "BOT1-05-T50_NC"
nombre_de_archivo = "BOT1-05-T50-TRIAXYSG3-NS09310-Z0-REALT-20260308-20260608.nc"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\06. Junio\\BOT1-05-T50\\DATOS"
df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2026-03-08 00:00:00  0.82   1.3  6.1  59.6    20.3
1 2026-03-08 01:00:00  0.82   1.3  6.3  58.0    20.4

In [9]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'Hs_BMT3-04-T45_C', 'Hmax_BMT3-04-T45_C', 'Tp_BMT3-04-T45_C',
       'dir_BMT3-04-T45_C', 'vardir_BMT3-04-T45_C', 'Hs_BMT3-04-T45_NC',
       'Hmax_BMT3-04-T45_NC', 'Tp_BMT3-04-T45_NC', 'dir_BMT3-04-T45_NC',
       'vardir_BMT3-04-T45_NC', 'Hs_BOT1-05-T50_NC', 'Hmax_BOT1-05-T50_NC',
       'Tp_BOT1-05-T50_NC', 'dir_BOT1-05-T50_NC', 'vardir_BOT1-05-T50_NC'],
      dtype='str')

In [11]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)