In [1]:
import os
import sys
# Agregar el directorio raíz del proyecto al path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..','..'))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)
    
    
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
# Iniciar un diccionario vacío para almacenar los DataFrames de cada boya
dict_de_boyas = {}

In [5]:
# listar_funciones_de_carga()

### 1. ADCP

In [6]:
p1 = pd.date_range('2026-02-13 21:00', '2026-05-01 12:00', freq='h') 
p2 = pd.date_range('2026-05-09 03:00', '2026-07-13 23:00', freq='h')
total = p1.append(p2)
print(f"p1 = {len(p1)}, p2 = {len(p2)}, total = {len(total)}")

p1 = 1840, p2 = 1581, total = 3421

In [7]:
# 1.3. p1: Crudo unido realt pkl
nombre = "BOT1-07-T80_pkl"
nombre_de_archivo = "msj4_crudo_unido_memrealt_2026021321_2026071323.pkl"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\07. Julio\\BOT1-07-T80\\DATOS"
df_pkl_C, _ = cargar_pickle_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_C # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_C.tail(2)

,tspan,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,rap_5,...,dir_13,rap_14,dir_14,rap_15,dir_15,rap_16,dir_16,rap_17,dir_17,temp_adcp
3601,2026-07-13 22:00:00,0.51,274.6,0.43,272.9,0.38,266.6,0.38,258.3,0.39,...,225.0,46.34,225.0,46.34,225.0,46.34,225.0,46.34,225.0,29.76
3602,2026-07-13 23:00:00,0.46,269.1,0.42,270.0,0.38,265.7,0.39,257.1,0.40,...,225.0,46.34,225.0,46.34,225.0,46.34,225.0,46.34,225.0,29.71

In [8]:
# 1.4. Cargar NETCDF de corrientes
nombre = "BOT1-07-T80_NC"
nombre_de_archivo = "BOT1-07-T80-SIG500DW-NS103971-Z0.54-MEMREALT-20260213-20260713.nc"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\07. Julio\\BOT1-07-T80\\DATOS"
df_nc, nc = cargar_nc_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

,tspan,temp_adcp,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,...,rap_10,dir_10,rap_11,dir_11,rap_12,dir_12,rap_13,dir_13,rap_14,dir_14
0,2026-02-13 21:00:00,24.379999,0.044586,42.636749,0.074219,175.595367,0.121915,187.398987,0.136676,190.923523,...,0.234230,198.442673,0.265157,194.680878,0.276854,194.026215,0.264001,193.873062,0.274585,196.111633
1,2026-02-13 22:00:00,24.400000,0.059192,204.876556,0.106976,211.818039,0.156634,221.946426,0.201619,225.864090,...,0.230845,190.053986,0.243647,178.871155,0.224770,175.917999,0.196400,180.029175,0.183386,187.299408

In [9]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BOT1-03-T50_datos_word_2026030618_2026070923.xlsx", variables="corrientes")

NAM correcto

     Variable  esperados  validados  porcentaje_validados
0          AE     3603.0     3306.0             91.756869
1   Temp adcp     3603.0     3393.0             94.171524
0       rap_1     3603.0     3389.0             94.060505
1       rap_2     3603.0     3393.0             94.171524
2       rap_3     3603.0     3393.0             94.171524
3       rap_4     3603.0     3392.0             94.143769
4       rap_5     3603.0     3392.0             94.143769
5       rap_6     3603.0     3388.0             94.032750
6       rap_7     3603.0     3387.0             94.004996
7       rap_8     3603.0     3387.0             94.004996
8       rap_9     3603.0     3371.0             93.560921
9      rap_10     3603.0     3293.0             91.396059
10     rap_11     3603.0     3188.0             88.481821
11     rap_12     3603.0     3002.0             83.319456
12     rap_13     3603.0     2625.0             72.855953
13     rap_14     3603.0     1861.0             51.651402

In [12]:
# 1.4. Cargar NETCDF de corrientes
nombre = "BOT1-03-T50_NC"
nombre_de_archivo = "BOT1-03-T50-SIG500DW-NS104017-Z0.54-MEMREALT-20260306-20260709.nc"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\07. Julio\\BOT1-03-T50\\DATOS"
df_nc, nc = cargar_nc_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

,tspan,temp_adcp,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,...,rap_8,dir_8,rap_9,dir_9,rap_10,dir_10,rap_11,dir_11,rap_12,dir_12
0,2026-03-06 18:00:00,25.40,0.084526,26.110329,0.094794,9.104601,0.066759,2.403809,0.055470,6.625356,...,0.062044,352.405334,0.037665,325.930206,0.045505,341.684479,0.081761,11.213730,0.068139,41.668449
1,2026-03-06 19:00:00,25.51,0.112771,12.495742,0.006859,7.539444,0.077781,199.762833,0.143961,195.387772,...,0.117931,199.157059,0.122795,186.922455,0.089229,183.083664,0.044378,230.210968,0.042865,298.418427

In [13]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'rap_1_BOT1-07-T80_pkl', 'dir_1_BOT1-07-T80_pkl',
       'rap_2_BOT1-07-T80_pkl', 'dir_2_BOT1-07-T80_pkl',
       'rap_3_BOT1-07-T80_pkl', 'dir_3_BOT1-07-T80_pkl',
       'rap_4_BOT1-07-T80_pkl', 'dir_4_BOT1-07-T80_pkl',
       'rap_5_BOT1-07-T80_pkl', 'dir_5_BOT1-07-T80_pkl',
       'rap_6_BOT1-07-T80_pkl', 'dir_6_BOT1-07-T80_pkl',
       'rap_7_BOT1-07-T80_pkl', 'dir_7_BOT1-07-T80_pkl',
       'rap_8_BOT1-07-T80_pkl', 'dir_8_BOT1-07-T80_pkl',
       'rap_9_BOT1-07-T80_pkl', 'dir_9_BOT1-07-T80_pkl',
       'rap_10_BOT1-07-T80_pkl', 'dir_10_BOT1-07-T80_pkl',
       'rap_11_BOT1-07-T80_pkl', 'dir_11_BOT1-07-T80_pkl',
       'rap_12_BOT1-07-T80_pkl', 'dir_12_BOT1-07-T80_pkl',
       'rap_13_BOT1-07-T80_pkl', 'dir_13_BOT1-07-T80_pkl',
       'rap_14_BOT1-07-T80_pkl', 'dir_14_BOT1-07-T80_pkl',
       'rap_15_BOT1-07-T80_pkl', 'dir_15_BOT1-07-T80_pkl',
       'rap_16_BOT1-07-T80_pkl', 'dir_16_BOT1-07-T80_pkl',
       'rap_17_BOT1-07-T80_pkl', 'dir_17_BOT1-07-T80_pkl',
       'temp_adcp_BOT1-07-T80_pkl', 'temp_adcp_BOT1-07-T80_NC',
       'rap_1_BOT1-07-T80_NC', 'dir_1_BOT1-07-T80_NC', 'rap_2_BOT1-07-T80_NC',
       'dir_2_BOT1-07-T80_NC', 'rap_3_BOT1-07-T80_NC', 'dir_3_BOT1-07-T80_NC',
       'rap_4_BOT1-07-T80_NC', 'dir_4_BOT1-07-T80_NC', 'rap_5_BOT1-07-T80_NC',
       'dir_5_BOT1-07-T80_NC', 'rap_6_BOT1-07-T80_NC', 'dir_6_BOT1-07-T80_NC',
       'rap_7_BOT1-07-T80_NC', 'dir_7_BOT1-07-T80_NC', 'rap_8_BOT1-07-T80_NC',
       'dir_8_BOT1-07-T80_NC', 'rap_9_BOT1-07-T80_NC', 'dir_9_BOT1-07-T80_NC',
       'rap_10_BOT1-07-T80_NC', 'dir_10_BOT1-07-T80_NC',
       'rap_11_BOT1-07-T80_NC', 'dir_11_BOT1-07-T80_NC',
       'rap_12_BOT1-07-T80_NC', 'dir_12_BOT1-07-T80_NC',
       'rap_13_BOT1-07-T80_NC', 'dir_13_BOT1-07-T80_NC',
       'rap_14_BOT1-07-T80_NC', 'dir_14_BOT1-07-T80_NC',
       'temp_adcp_BOT1-03-T50_NC', 'rap_1_BOT1-03-T50_NC',
       'dir_1_BOT1-03-T50_NC', 'rap_2_BOT1-03-T50_NC', 'dir_2_BOT1-03-T50_NC',
       'rap_3_BOT1-03-T50_NC', 'dir_3_BOT1-03-T50_NC', 'rap_4_BOT1-03-T50_NC',
       'dir_4_BOT1-03-T50_NC', 'rap_5_BOT1-03-T50_NC', 'dir_5_BOT1-03-T50_NC',
       'rap_6_BOT1-03-T50_NC', 'dir_6_BOT1-03-T50_NC', 'rap_7_BOT1-03-T50_NC',
       'dir_7_BOT1-03-T50_NC', 'rap_8_BOT1-03-T50_NC', 'dir_8_BOT1-03-T50_NC',
       'rap_9_BOT1-03-T50_NC', 'dir_9_BOT1-03-T50_NC', 'rap_10_BOT1-03-T50_NC',
       'dir_10_BOT1-03-T50_NC', 'rap_11_BOT1-03-T50_NC',
       'dir_11_BOT1-03-T50_NC', 'rap_12_BOT1-03-T50_NC',
       'dir_12_BOT1-03-T50_NC'],
      dtype='str')

In [14]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)