In [1]:
import os
import sys
# Agregar el directorio raíz del proyecto al path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..','..'))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)
    
    
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
dict_de_boyas = {}

### 2. OLEAJE

In [5]:
p1 = pd.date_range('2026-02-28 17:00', '2026-07-10 23:00', freq='h') 
print(f"p1 = {len(p1)}")

p1 = 3175

In [6]:
# p1: Crudo unido pkl
nombre = "BMT2-01-T20_pkl"
archivo = "msj4_crudo_unido_realt_2026022817_2026071023.pkl"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_3.2\\2026\\07. Julio\\BMT2-01-T20\\DATOS"
df_pkl_crudo_realt, prof = cargar_pickle_adcp(ruta_a_carpeta, archivo)
dict_de_boyas[nombre] = df_pkl_crudo_realt # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_crudo_realt.head(5)

,tspan,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,rap_5,dir_5,rap_6,dir_6,temp_adcp,temperatura_mct,conductividad_mct,salinidad_mct
0,2026-02-28 17:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-02-28 18:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-02-28 19:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-02-28 20:00:00,0.06,281.9,0.12,268.6,0.12,250.5,0.10,240.1,0.01,315.0,46.34,225.0,26.45,26.2592,5.71911,37.0384
4,2026-02-28 21:00:00,0.04,298.6,0.15,273.5,0.15,261.9,46.34,225.0,0.00,225.0,46.34,225.0,26.05,25.8258,5.67207,37.0439

In [7]:
# 1.5. p2: Cargar NETCDF 
nombre = "BMT2-01-T20_NC"
nombre_de_archivo = "BMT2-01-T20-SIG500DW-NS106075-Z1-REALT-20260228-20260710.nc"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_3.2\\2026\\07. Julio\\BMT2-01-T20\\DATOS"
df_nc, nc = cargar_nc_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

,tspan,temp_adcp,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4
0,2026-02-28 20:00:00,26.450001,0.06,281.899963,0.12,268.599976,0.12,250.499985,0.1,240.099991
1,2026-02-28 21:00:00,26.049999,0.04,298.600006,0.15,273.500000,0.15,261.899994,NaN,NaN

In [8]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BMT2-01-T20_datos_word_2026022820_2026071023.xlsx", variables="corrientes")

NAM correcto

    Variable  esperados  validados  porcentaje_validados
0         AE     3172.0     3133.0             98.770492
1  Temp adcp     3172.0     3147.0             99.211854
0      rap_1     3172.0     2694.0             84.930643
1      rap_2     3172.0     3145.0             99.148802
2      rap_3     3172.0     3144.0             99.117276
3      rap_4     3172.0     2705.0             85.277427

In [ ]:
# 1.5. p2: Cargar NETCDF 
nombre = "BMT2-01-T20_MCT_NC"
nombre_de_archivo = "BMT2-01-T20-MCT-NS26047-Z1-REALT-20260228-20260710.nc"
df_nc, nc = cargar_nc_MCT(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

In [9]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'rap_1_BMT2-01-T20_pkl', 'dir_1_BMT2-01-T20_pkl',
       'rap_2_BMT2-01-T20_pkl', 'dir_2_BMT2-01-T20_pkl',
       'rap_3_BMT2-01-T20_pkl', 'dir_3_BMT2-01-T20_pkl',
       'rap_4_BMT2-01-T20_pkl', 'dir_4_BMT2-01-T20_pkl',
       'rap_5_BMT2-01-T20_pkl', 'dir_5_BMT2-01-T20_pkl',
       'rap_6_BMT2-01-T20_pkl', 'dir_6_BMT2-01-T20_pkl',
       'temp_adcp_BMT2-01-T20_pkl', 'temperatura_mct_BMT2-01-T20_pkl',
       'conductividad_mct_BMT2-01-T20_pkl', 'salinidad_mct_BMT2-01-T20_pkl',
       'temp_adcp_BMT2-01-T20_NC', 'rap_1_BMT2-01-T20_NC',
       'dir_1_BMT2-01-T20_NC', 'rap_2_BMT2-01-T20_NC', 'dir_2_BMT2-01-T20_NC',
       'rap_3_BMT2-01-T20_NC', 'dir_3_BMT2-01-T20_NC', 'rap_4_BMT2-01-T20_NC',
       'dir_4_BMT2-01-T20_NC'],
      dtype='str')

In [10]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)

In [ ]:
# idxs = app.deletion_log["vardir_BOT1-04-T80_pkl_realt_V"]["idxs"]
# tspan_num = mdates.num2date(app.data.loc[idxs,"tspan"])
# tspan_pd = pd.to_datetime(tspan_num)
# df_out = pd.DataFrame({"tspan": tspan_pd})
# df_out.to_csv("tspan_eliminados.csv", index=False)