In [1]:
import os
import sys
# Agregar el directorio raíz del proyecto al path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..','..'))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)
    
    
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
dict_de_boyas = {}

### 2. OLEAJE

In [5]:
p1 = pd.date_range('2025-11-01 15:00', '2026-04-23 19:00', freq='h') 
p2 = pd.date_range('2026-04-26 16:00', '2026-07-09 23:00', freq='h')
total = p1.append(p2)
print(f"p1 = {len(p1)}, p2 = {len(p2)}, total = {len(total)}")

p1 = 4157, p2 = 1784, total = 5941

In [6]:
# p1: Crudo unido pkl
nombre = "BOT1-04-T80_pkl_memrealt"
archivos_csv = "msj3_crudo_unido_mem_2025110115_2026042319.pkl"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\07. Julio\\BOT1-04-T80\\DATOS"
df_pkl_crudo_realt_1 = cargar_pickle_oleaje(ruta_a_carpeta, archivos_csv)

archivos_csv = "msj3_crudo_unido_realt_2026042616_2026070923.pkl"
df_pkl_crudo_realt_2= cargar_pickle_oleaje(ruta_a_carpeta, archivos_csv)

df_pkl_crudo_men_realt = pd.concat([df_pkl_crudo_realt_1, df_pkl_crudo_realt_2]).reset_index(drop=True)
dict_de_boyas[nombre] = df_pkl_crudo_men_realt # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_crudo_men_realt.head(2)

                tspan    Hs  Hmax   Tp    dir  vardir
0 2025-11-01 15:00:00  0.66  1.02  6.7  344.0    35.0
1 2025-11-01 16:00:00  0.69  1.12  6.2  352.0    33.0

In [7]:
df_pkl_crudo_men_realt.tail(2)

                   tspan    Hs  Hmax   Tp   dir  vardir
5939 2026-07-09 22:00:00  0.93  1.62  5.4  50.1    33.7
5940 2026-07-09 23:00:00  0.86  1.37  5.7  48.8    35.6

In [8]:
# 1.5. p1: Cargar NETCDF 
nombre = "BOT1-04-T80_NC1"
nombre_de_archivo = "BOT1-04-T80-TRIAXYSG3-NS09294-Z0-MEM-20251101-20260423.nc"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\07. Julio\\BOT1-04-T80\\DATOS"
df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp  dir  vardir
0 2025-11-01 15:00:00  0.66  1.02  6.7  NaN     NaN
1 2025-11-01 16:00:00  0.69  1.12  6.2  NaN     NaN

In [9]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BOT1-04-T80_datos_word_2026032500_2026070923.xlsx", variables="oleaje")

NAM correcto

  Variable  esperados  validados  porcentaje_validados
0       Hs       4157     4155.0             99.951888
1       Hm       4157     4155.0             99.951888
2       Tp       4157     4155.0             99.951888
3      dir       4157        0.0              0.000000
4   vardir       4157        0.0              0.000000
5  dirspec       4157     4156.0             99.975944

In [10]:
# DirSpec

In [11]:
# 1.5. p1: Cargar NETCDF 
nombre = "BOT1-04-T80_NC2"
nombre_de_archivo = "BOT1-04-T80-TRIAXYSG3-NS09186-Z0-REALT-20260426-20260709.nc"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\07. Julio\\BOT1-04-T80\\DATOS"
df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

                tspan    Hs  Hmax   Tp   dir  vardir
0 2026-04-26 16:00:00  0.48  0.74  4.8  66.7    43.5
1 2026-04-26 17:00:00  0.53  0.80  5.0  54.9    32.4

In [12]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BOT1-04-T80_datos_word_2026042616_2026070923.xlsx", variables="oleaje")

NAM correcto

  Variable  esperados  validados  porcentaje_validados
0       Hs       1784     1782.0             99.887892
1       Hm       1784     1782.0             99.887892
2       Tp       1784     1782.0             99.887892
3      dir       1784     1782.0             99.887892
4   vardir       1784     1782.0             99.887892
5  dirspec       1784     1724.0             96.636771

In [13]:
nombre = "BOT1-03-T50"
df_pkl = pd.DataFrame()  # Inicializar un DataFrame vacío para almacenar los datos combinados
for mes in ["11. Noviembre","12. Diciembre"]:
    ruta_a_carpeta = f"\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.4\\2025\\{mes}\\BOT1-03-T50\\DATOS"
    archivos = os.listdir(ruta_a_carpeta)
    for archivo in archivos:
        if archivo.endswith(".pkl"):
            if archivo.startswith("msj3_validados_realt"):
                df_pkl_crudo_realt = cargar_pickle_oleaje(ruta_a_carpeta, archivo)
                df_pkl = pd.concat([df_pkl, df_pkl_crudo_realt], ignore_index=True)
    

for mes in ["01. Enero","02. Febrero","03. Marzo","04. Abril","05. Mayo", "06. Junio"]:
    ruta_a_carpeta = f"\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.4\\2026\\{mes}\\BOT1-03-T50\\DATOS"
    archivos = os.listdir(ruta_a_carpeta)
    for archivo in archivos:
        if archivo.endswith(".pkl"):
            if archivo.startswith("msj3_validados_realt"):
                df_pkl_crudo_realt = cargar_pickle_oleaje(ruta_a_carpeta, archivo)
                df_pkl = pd.concat([df_pkl, df_pkl_crudo_realt], ignore_index=True)
    
df_pkl = df_pkl.reset_index(drop=True)  # Reiniciar el índice del DataFrame combinado
dict_de_boyas[nombre] = df_pkl # Guardo el dataframe combinado dentro del diccionario de boyas.

In [14]:
nombre = "BOT1-05-T50"
df_pkl = pd.DataFrame()  # Inicializar un DataFrame vacío para almacenar los datos combinados
for mes in ["11. Noviembre","12. Diciembre"]:
    ruta_a_carpeta = f"\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.4\\2025\\{mes}\\BOT1-05-T50\\DATOS"
    archivos = os.listdir(ruta_a_carpeta)
    for archivo in archivos:
        if archivo.endswith(".pkl"):
            if archivo.startswith("msj3_validados_realt"):
                df_pkl_crudo_realt = cargar_pickle_oleaje(ruta_a_carpeta, archivo)
                df_pkl = pd.concat([df_pkl, df_pkl_crudo_realt], ignore_index=True)


for mes in ["01. Enero","02. Febrero","03. Marzo","04. Abril","05. Mayo", "06. Junio"]:
    ruta_a_carpeta = f"\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.4\\2026\\{mes}\\BOT1-05-T50\\DATOS"
    archivos = os.listdir(ruta_a_carpeta)
    for archivo in archivos:
        if archivo.endswith(".pkl"):
            if archivo.startswith("msj3_validados_realt"):
                df_pkl_crudo_realt = cargar_pickle_oleaje(ruta_a_carpeta, archivo)
                df_pkl = pd.concat([df_pkl, df_pkl_crudo_realt], ignore_index=True)
    
df_pkl = df_pkl.reset_index(drop=True)  # Reiniciar el índice del DataFrame combinado
dict_de_boyas[nombre] = df_pkl # Guardo el dataframe combinado dentro del diccionario de boyas.

In [15]:
# nombre = "BOT1-07-T80"
# df_pkl = pd.DataFrame()  # Inicializar un DataFrame vacío para almacenar los datos combinados
# for mes in ["11. Noviembre","12. Diciembre"]:
#     ruta_a_carpeta = f"\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.4\\2025\\{mes}\\BOT1-07-T80\\DATOS"
#     archivos = os.listdir(ruta_a_carpeta)
#     for archivo in archivos:
#         if archivo.endswith(".pkl"):
#             if archivo.startswith("msj3_validados_realt"):
#                 df_pkl_crudo_realt = cargar_pickle_oleaje(ruta_a_carpeta, archivo)
#                 df_pkl = pd.concat([df_pkl, df_pkl_crudo_realt], ignore_index=True)

# for mes in ["01. Enero","02. Febrero","03. Marzo","04. Abril","05. Mayo", "06. Junio"]:
#     ruta_a_carpeta = f"\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.4\\2026\\{mes}\\BOT1-07-T80\\DATOS"
#     archivos = os.listdir(ruta_a_carpeta)
#     for archivo in archivos:
#         if archivo.endswith(".pkl"):
#             if archivo.startswith("msj3_validados_realt"):
#                 df_pkl_crudo_realt = cargar_pickle_oleaje(ruta_a_carpeta, archivo)
#                 df_pkl = pd.concat([df_pkl, df_pkl_crudo_realt], ignore_index=True)
    
# df_pkl = df_pkl.reset_index(drop=True)  # Reiniciar el índice del DataFrame combinado
# dict_de_boyas[nombre] = df_pkl # Guardo el dataframe combinado dentro del diccionario de boyas.

In [16]:
# # 1.5. p2: Cargar NETCDF 
# nombre = "BOT1-03-T50_NC"
# nombre_de_archivo = "BOT1-03-T50-TRIAXYSG3-NS09295-Z0-MEMREALT-20260306-20260709.nc"
# ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\07. Julio\\BOT1-03-T50\\DATOS"
# df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
# dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
# df_nc.head(2)

In [17]:
# # 1.5. p2: Cargar NETCDF 
# nombre = "BOT1-07-T80_NC"
# nombre_de_archivo = "BOT1-07-T80-TRIAXYSG3-NS09171-Z0-MEMREALT-20260213-20260713.nc"
# ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\07. Julio\\BOT1-07-T80\\DATOS"
# df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
# dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
# df_nc.head(2)

In [18]:
# # 1.5. p2: Cargar NETCDF 
# nombre = "BOT1-05-T50_NC"
# nombre_de_archivo = "BOT1-05-T50-TRIAXYSG3-NS09310-Z0-REALT-20260301-20260714.nc"
# ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\07. Julio\\BOT1-05-T50\\DATOS"
# df_nc, nc, DirSpec = cargar_nc_oleaje(ruta_a_carpeta, nombre_de_archivo)
# dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
# df_nc.head(2)

In [19]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'Hs_BOT1-04-T80_pkl_memrealt', 'Hmax_BOT1-04-T80_pkl_memrealt',
       'Tp_BOT1-04-T80_pkl_memrealt', 'dir_BOT1-04-T80_pkl_memrealt',
       'vardir_BOT1-04-T80_pkl_memrealt', 'Hs_BOT1-04-T80_NC1',
       'Hmax_BOT1-04-T80_NC1', 'Tp_BOT1-04-T80_NC1', 'dir_BOT1-04-T80_NC1',
       'vardir_BOT1-04-T80_NC1', 'Hs_BOT1-04-T80_NC2', 'Hmax_BOT1-04-T80_NC2',
       'Tp_BOT1-04-T80_NC2', 'dir_BOT1-04-T80_NC2', 'vardir_BOT1-04-T80_NC2',
       'Hs_BOT1-03-T50', 'Hmax_BOT1-03-T50', 'Tp_BOT1-03-T50',
       'dir_BOT1-03-T50', 'vardir_BOT1-03-T50', 'Hs_BOT1-05-T50',
       'Hmax_BOT1-05-T50', 'Tp_BOT1-05-T50', 'dir_BOT1-05-T50',
       'vardir_BOT1-05-T50'],
      dtype='str')

In [20]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)

In [21]:
# idxs = app.deletion_log["vardir_BOT1-04-T80_pkl_realt_V"]["idxs"]
# tspan_num = mdates.num2date(app.data.loc[idxs,"tspan"])
# tspan_pd = pd.to_datetime(tspan_num)
# df_out = pd.DataFrame({"tspan": tspan_pd})
# df_out.to_csv("tspan_eliminados.csv", index=False)