In [1]:
import os
import sys
# Agregar el directorio raíz del proyecto al path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..', '..','..'))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)
    
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *   
from services.utilidades import *
from services.comprobar_netcdf import *

In [2]:
# Recargar módulos locales (ejecutar esta celda cuando cambies código en services/)
import importlib
import sys

# Lista de módulos locales a recargar
modulos_locales = [
    'services.carga_de_datos',
    'services.DataFrame_maker',
    'services.prueba',
    'services.utilidades',
    'services.get_tspan',
    'services.polar2uv',
    'services.uv2polar'
]

for modulo in modulos_locales:
    if modulo in sys.modules:
        importlib.reload(sys.modules[modulo])
        print(f"✓ Recargado: {modulo}")
    else:
        print(f"- No cargado: {modulo}")

# Re-importar después de recargar
from services.DataFrame_maker import *
from services.InteractivePlotter import InteractivePlotterTk
from services.carga_de_datos import *

print("\n¡Módulos locales recargados!")

✓ Recargado: services.carga_de_datos
✓ Recargado: services.DataFrame_maker
- No cargado: services.prueba
✓ Recargado: services.utilidades
✓ Recargado: services.get_tspan
✓ Recargado: services.polar2uv
✓ Recargado: services.uv2polar

¡Módulos locales recargados!

In [3]:
# %matplotlib tk

In [4]:
# Iniciar un diccionario vacío para almacenar los DataFrames de cada boya
dict_de_boyas = {}

In [5]:
# listar_funciones_de_carga()

### 1. ADCP

In [6]:
p1 = pd.date_range('2026-03-01 00:00', '2026-06-27 01:00', freq='h') 
total = p1
print(f"p1 = {len(p1)}, total = {len(total)}")

p1 = 2834, total = 2834

In [7]:
# p1: Crudo unido pkl
nombre = "BOT1-10-T40_pkl"
nombre_de_archivo = "msj4_crudo_unido_realt_2026030100_2026062701.pkl"
ruta_a_carpeta = "\\\\192.168.15.249\\Med_2025-2026\\Reportes_Edit\\Reporte_1.2\\2026\\07. Julio\\BOT1-10-T40\\DATOS"
df_pkl_C, _ = cargar_pickle_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_pkl_C # Guardo el dataframe dentro del diccionario de boyas.
df_pkl_C.tail(2)

,tspan,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,rap_5,...,dir_6,rap_7,dir_7,rap_8,dir_8,rap_9,dir_9,rap_10,dir_10,temp_adcp
2832,2026-06-27 00:00:00,0.28,274.2,0.27,275.8,0.22,271.8,0.20,268.3,0.21,...,261.5,0.22,258.2,0.19,255.3,0.04,256.7,46.34,225.0,29.48
2833,2026-06-27 01:00:00,0.30,261.2,0.28,262.4,0.24,260.5,0.23,257.1,0.22,...,255.6,0.22,253.2,0.19,250.1,0.05,214.4,46.34,225.0,29.43

In [8]:
# 1.4. Cargar NETCDF de corrientes
nombre = "BOT1-10-T40_NC"
nombre_de_archivo = "BOT1-10-T40-SIG500DW-NS103996-Z0.54-REALT-20260301-20260627.nc"
df_nc, nc = cargar_nc_adcp(ruta_a_carpeta, nombre_de_archivo)
dict_de_boyas[nombre] = df_nc # Guardo el dataframe dentro del diccionario de boyas.
df_nc.head(2)

,tspan,temp_adcp,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,rap_5,dir_5,rap_6,dir_6,rap_7,dir_7,rap_8,dir_8,rap_9,dir_9
0,2026-03-01 00:00:00,24.790001,0.15,309.899994,0.14,338.100006,0.1,321.300018,0.09,307.500000,0.09,311.300018,0.09,311.100006,0.09,298.999969,0.06,292.199982,0.01,259.700012
1,2026-03-01 01:00:00,24.559999,0.13,310.699982,0.15,346.599976,0.1,350.599976,0.07,337.200012,0.07,331.199982,0.08,330.399994,0.07,310.000000,0.05,289.200012,0.03,311.199982

In [9]:
df_nc.tail(2)

,tspan,temp_adcp,rap_1,dir_1,rap_2,dir_2,rap_3,dir_3,rap_4,dir_4,rap_5,dir_5,rap_6,dir_6,rap_7,dir_7,rap_8,dir_8,rap_9,dir_9
2832,2026-06-27 00:00:00,29.48,0.28,274.200012,0.27,275.799988,0.22,271.799988,0.20,268.299988,0.21,264.000000,0.22,261.500000,0.22,258.199982,0.19,255.300003,0.04,256.699982
2833,2026-06-27 01:00:00,29.43,0.30,261.200012,0.28,262.399994,0.24,260.500000,0.23,257.100006,0.22,256.600006,0.22,255.599976,0.22,253.199982,0.19,250.099991,0.05,214.399994

In [10]:
# Otras revisiones del NC:
# comprobar_nombre_nc
comprobar_nombre_nc(nombre_de_archivo, nc)
comprobar_porcentaje_de_variable(nc, ruta_a_carpeta, "BOT1-10-T40_datos_word_2026030100_2026062701.xlsx", variables="corrientes")

NAM correcto

    Variable  esperados  validados  porcentaje_validados
0         AE     2834.0     2808.0             99.082569
1  Temp adcp     2834.0     2811.0             99.188426
0      rap_1     2834.0     2808.0             99.082569
1      rap_2     2834.0     2806.0             99.011997
2      rap_3     2834.0     2808.0             99.082569
3      rap_4     2834.0     2482.0             87.579393
4      rap_5     2834.0     2481.0             87.544107
5      rap_6     2834.0     2397.0             84.580099
6      rap_7     2834.0     2360.0             83.274524
7      rap_8     2834.0     2349.0             82.886380
8      rap_9     2834.0     2387.0             84.227241

In [11]:
# Crear el diccionario de boyas con los dataframes cargados
df = crear_dataframe_de_boyas(dict_de_boyas)

Index(['tspan', 'rap_1_BOT1-10-T40_pkl', 'dir_1_BOT1-10-T40_pkl',
       'rap_2_BOT1-10-T40_pkl', 'dir_2_BOT1-10-T40_pkl',
       'rap_3_BOT1-10-T40_pkl', 'dir_3_BOT1-10-T40_pkl',
       'rap_4_BOT1-10-T40_pkl', 'dir_4_BOT1-10-T40_pkl',
       'rap_5_BOT1-10-T40_pkl', 'dir_5_BOT1-10-T40_pkl',
       'rap_6_BOT1-10-T40_pkl', 'dir_6_BOT1-10-T40_pkl',
       'rap_7_BOT1-10-T40_pkl', 'dir_7_BOT1-10-T40_pkl',
       'rap_8_BOT1-10-T40_pkl', 'dir_8_BOT1-10-T40_pkl',
       'rap_9_BOT1-10-T40_pkl', 'dir_9_BOT1-10-T40_pkl',
       'rap_10_BOT1-10-T40_pkl', 'dir_10_BOT1-10-T40_pkl',
       'temp_adcp_BOT1-10-T40_pkl', 'temp_adcp_BOT1-10-T40_NC',
       'rap_1_BOT1-10-T40_NC', 'dir_1_BOT1-10-T40_NC', 'rap_2_BOT1-10-T40_NC',
       'dir_2_BOT1-10-T40_NC', 'rap_3_BOT1-10-T40_NC', 'dir_3_BOT1-10-T40_NC',
       'rap_4_BOT1-10-T40_NC', 'dir_4_BOT1-10-T40_NC', 'rap_5_BOT1-10-T40_NC',
       'dir_5_BOT1-10-T40_NC', 'rap_6_BOT1-10-T40_NC', 'dir_6_BOT1-10-T40_NC',
       'rap_7_BOT1-10-T40_NC', 'dir_7_BOT1-10-T40_NC', 'rap_8_BOT1-10-T40_NC',
       'dir_8_BOT1-10-T40_NC', 'rap_9_BOT1-10-T40_NC', 'dir_9_BOT1-10-T40_NC'],
      dtype='str')

In [12]:
app = InteractivePlotterTk(df)
# Iniciar el bucle de la aplicación
app.root.mainloop()

# NOTAS PENDIENTES:
# - Arreglar que al eliminar puntos para que no tenga límite el historial de deshacer
# - Arreglar para que solo se grafiquen las columnas elegidas por el usuario
# - Agregar una función que grafique las variables de Rap y Dir --> sería algo como que df.iloc[idx,col][prof]
# - Arreglar el caso de cuando el usuario elimina puntos de Rap o Dir colocar U y V como nans --> df.iloc[idx,col][prof] = np.nan
# - Agregar la funcionalidad de guardar el DataFrame corregido en un archivo .csv o .xlsx, pkl
# - Agregar la funcionalidad de devolver puntos eliminados (no deshacer la última acción, sino devolver puntos específicos)